Retry connect with allow_agent=False if connect fails
For some reason when I use reviewtodo from work I need to set
allow_agent=False. This works fine for me without allow_agent=False
from the same computer from home though (not sure why). This patch adds logic
to retry the connect with allow_agent=False if the connect
raises paramiko.SSHException.

Traceback (most recent call last):
  File "/usr/local/bin/reviewtodo", line 10, in <module>
    sys.exit(main())
  File "/home/arosen/reviewtodo/reviewtodo/main.py", line 161, in main
    print_review_todo(options)
  File "/home/arosen/reviewtodo/reviewtodo/main.py", line 74, in print_review_todo
    options.server)
  File "/home/arosen/reviewtodo/reviewtodo/main.py", line 41, in get_changes
    allow_agent=True)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 342, in connect
    self._auth(username, password, pkey, key_filenames, allow_agent, look_for_keys)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 533, in _auth
    raise saved_exception
paramiko.SSHException: No existing session